In [1]:
import duckdb

con = duckdb.connect(database=':memory:')
counts = con.execute("""
    SELECT repair, COUNT(*) as count
    FROM 'cleanml.csv' 
    WHERE fairness_impact = 'positive' and error = 'missing_values'
    GROUP BY repair
    ORDER BY repair
""").df()

counts

                repair  count
0    impute_mean_dummy      9
1     impute_mean_mode      5
2  impute_median_dummy      7
3   impute_median_mode      5
4    impute_mode_dummy      6
5     impute_mode_mode      5

In [2]:
import duckdb

con = duckdb.connect(database=':memory:')
counts = con.execute("""
    SELECT repair LIKE '%dummy' as dummy, COUNT(*) as count
    FROM 'cleanml.csv' 
    WHERE fairness_impact = 'positive' and error = 'missing_values'
    GROUP BY dummy
    ORDER BY dummy
""").df()

counts

   dummy  count
0  False     15
1   True     22

In [3]:
import duckdb

con = duckdb.connect(database=':memory:')
counts = con.execute("""
    SELECT detection, repair, COUNT(*) as count
    FROM 'cleanml.csv' 
    WHERE fairness_impact = 'positive' and error = 'outliers'
    GROUP BY detection, repair
    ORDER BY detection, repair
""").df()

counts

  detection                repair  count
0        IF    impute__mean_dummy      4
1        IF  impute__median_dummy      3
2        IF    impute__mode_dummy      4
3       IQR    impute__mean_dummy      1
4       IQR  impute__median_dummy      2
5       IQR    impute__mode_dummy      1
6        SD    impute__mean_dummy      5
7        SD  impute__median_dummy      4
8        SD    impute__mode_dummy      7

In [4]:
import duckdb

con = duckdb.connect(database=':memory:')
counts = con.execute("""
    SELECT detection, repair, COUNT(*) as count
    FROM 'cleanml.csv' 
    WHERE fairness_impact = 'positive' and error = 'outliers'
    GROUP BY detection, repair
    ORDER BY detection, repair
""").df()

counts

  detection                repair  count
0        IF    impute__mean_dummy      4
1        IF  impute__median_dummy      3
2        IF    impute__mode_dummy      4
3       IQR    impute__mean_dummy      1
4       IQR  impute__median_dummy      2
5       IQR    impute__mode_dummy      1
6        SD    impute__mean_dummy      5
7        SD  impute__median_dummy      4
8        SD    impute__mode_dummy      7

In [5]:
import duckdb

con = duckdb.connect(database=':memory:')
counts = con.execute("""
    SELECT detection, COUNT(*) as count
    FROM 'cleanml.csv' 
    WHERE fairness_impact = 'positive' and error = 'outliers'
    GROUP BY detection
    ORDER BY detection
""").df()

counts

  detection  count
0        IF     11
1       IQR      4
2        SD     16